### ISSUE TITLE
Projects 2: arguments type/order issue

### ISSUE THREAD

**Issue by rickecon** [nyupredocs/githubtutorial#4]
What order of elements should you use for an `args` tuple, and how will you communicate it? An interesting question was brought up about the `args` input argument and the order of its elements. For a tuple, the order of the elements matters. For a Python dictionary, the order does not matter, but it gets unpacked differently. There is another cool approach in a new repo called [ParamTools](https://github.com/PSLmodels/ParamTools) that creates a parameters class.

**Comment by evanjflack** [comment]
Looks like this is being addressed here 

https://github.com/nyupredocs/githubtutorial/issues/6

**Comment by evanjflack** [comment]
Issue #6

**Comment by rickecon** [comment]
This is addressed in Issue #6 as well. It is implemented in PR #15  and some bugs fixed in PR #21.
