### ISSUE TITLE
Argument orders

### ISSUE THREAD

**Issue by glesnick** [nyupredocs/githubtutorial#6]
The exercise 3 team needs argument orders defined for all function we need to call. Could exercise 1/2 teams please confirm or amend these proposed arguments:
- FirmsMC.get_r(b2, (nvec, alpha, A, delta))
- FirmsMC.get_w(b2, (nvec, alpha, A))
- household.get_c1(b2, (nvec, alpha, A, n1))
- household.get_c2(b2, (nvec, alpha, A, delta, n2))
- household.get_MUc(c, gamma)

**Comment by nadavtadelis** [comment]
Can confirm that FirmsMC are in that order @glesnick

**Comment by glesnick** [comment]
Please ignore n* I forgot those are part of nvec

**Comment by rickecon** [comment]
Who shall we "at" (Group 1: @evanjflack @nadavtadelis) (Group 2: @joel-becker @EdJeeOnGitHub )

**Comment by glesnick** [comment]
In general (to extend this to our functions), we will assume
`args = (nvec, alpha, A, delta, beta)`

**Comment by glesnick** [comment]
Update - we also need gamma:
`args = (nvec, alpha, A, delta, beta, gamma)`

**Comment by rickecon** [comment]
This is a great change. If we were really going to do this right, we would use the [ParamTools](https://github.com/PSLmodels/ParamTools) package. This change looks good and is implemented in PR #15 and some bugs fixed in PR #21.
